version: "3.8"

services:
  kuala-api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "deno", "eval", "fetch('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
